**Assignment Problem**

In [1]:
import numpy as np

def hungarian_method(cost_matrix):

    for i in range(len(cost_matrix)):
        cost_matrix[i] -= cost_matrix[i].min()


    for j in range(len(cost_matrix[0])):
        cost_matrix[:, j] -= cost_matrix[:, j].min()


    def cover_zeros(matrix):
        n = len(matrix)
        row_cover = [False] * n
        col_cover = [False] * n
        zero_marks = np.zeros_like(matrix, dtype=int)

        while True:

            for i in range(n):
                for j in range(n):
                    if matrix[i][j] == 0 and not row_cover[i] and not col_cover[j]:
                        zero_marks[i][j] = 1
                        row_cover[i] = True
                        col_cover[j] = True
                        break


            row_cover = [False] * n
            col_cover = [False] * n


            for i in range(n):
                if 1 in zero_marks[i]:
                    row_cover[i] = True
            for j in range(n):
                if 1 in zero_marks[:, j]:
                    col_cover[j] = True

            covered_rows = sum(row_cover)
            covered_cols = sum(col_cover)
            if covered_rows + covered_cols >= n:
                break


            uncovered_min = float('inf')
            for i in range(n):
                for j in range(n):
                    if not row_cover[i] and not col_cover[j]:
                        uncovered_min = min(uncovered_min, matrix[i][j])

            for i in range(n):
                for j in range(n):
                    if not row_cover[i] and not col_cover[j]:
                        matrix[i][j] -= uncovered_min
                    if row_cover[i] and col_cover[j]:
                        matrix[i][j] += uncovered_min

        return zero_marks


    zero_marks = cover_zeros(cost_matrix.copy())
    assignment = np.zeros_like(cost_matrix, dtype=int)

    for i in range(len(cost_matrix)):
        for j in range(len(cost_matrix[i])):
            if zero_marks[i][j] == 1:
                assignment[i][j] = 1

    return assignment


cost = [
    [120,100,80,90],
    [80,90,110,70],
    [110,140,120,100],
    [90,90,80,90]
]

cost_matrix = np.array(cost, dtype=float)
assignment_matrix = hungarian_method(cost_matrix.copy())
total_cost = np.sum(cost_matrix * assignment_matrix)

print("Assignment Matrix:")
print(assignment_matrix)
print(f"Total Cost: {total_cost}")


Assignment Matrix:
[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
Total Cost: 350.0


In [2]:
import numpy as np

def hungarian_method(cost_matrix):

    for i in range(len(cost_matrix)):
        cost_matrix[i] -= cost_matrix[i].min()


    for j in range(len(cost_matrix[0])):
        cost_matrix[:, j] -= cost_matrix[:, j].min()


    def cover_zeros(matrix):
        n = len(matrix)
        row_cover = [False] * n
        col_cover = [False] * n
        zero_marks = np.zeros_like(matrix, dtype=int)

        while True:

            for i in range(n):
                for j in range(n):
                    if matrix[i][j] == 0 and not row_cover[i] and not col_cover[j]:
                        zero_marks[i][j] = 1
                        row_cover[i] = True
                        col_cover[j] = True
                        break


            row_cover = [False] * n
            col_cover = [False] * n


            for i in range(n):
                if 1 in zero_marks[i]:
                    row_cover[i] = True
            for j in range(n):
                if 1 in zero_marks[:, j]:
                    col_cover[j] = True

            covered_rows = sum(row_cover)
            covered_cols = sum(col_cover)
            if covered_rows + covered_cols >= n:
                break


            uncovered_min = float('inf')
            for i in range(n):
                for j in range(n):
                    if not row_cover[i] and not col_cover[j]:
                        uncovered_min = min(uncovered_min, matrix[i][j])

            for i in range(n):
                for j in range(n):
                    if not row_cover[i] and not col_cover[j]:
                        matrix[i][j] -= uncovered_min
                    if row_cover[i] and col_cover[j]:
                        matrix[i][j] += uncovered_min

        return zero_marks


    zero_marks = cover_zeros(cost_matrix.copy())
    assignment = np.zeros_like(cost_matrix, dtype=int)

    for i in range(len(cost_matrix)):
        for j in range(len(cost_matrix[i])):
            if zero_marks[i][j] == 1:
                assignment[i][j] = 1

    return assignment


cost = [
    [4, 3, 6, 2, 7],
    [10, 12, 11, 14, 16],
    [4, 3, 2, 1, 5],
    [8, 7, 6, 9, 6]
]

cost_matrix = np.array(cost, dtype=float)
assignment_matrix = hungarian_method(cost_matrix.copy())
total_cost = np.sum(cost_matrix * assignment_matrix)

print("Assignment Matrix:")
print(assignment_matrix)
print(f"Total Cost: {total_cost}")


Assignment Matrix:
[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]]
Total Cost: 20.0
